[package]
name = "umbral-pre"
version = "0.2.0"
authors = ["Bogdan Opanchuk <bogdan@opanchuk.net>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Implementation of Umbral proxy reencryption algorithm"
repository = "https://github.com/nucypher/rust-umbral/tree/master/umbral-pre"
readme = "README.md"
categories = ["cryptography", "no-std"]

[dependencies]
k256 = { version = "0.8", default-features = false, features = ["ecdsa", "arithmetic"] }
sha2 = "0.9"
chacha20poly1305 = { version = "0.8", features = ["xchacha20poly1305"] }
hkdf = "0.11"
hex = "0.4"

# These packages are among the dependencies of the packages above.
# Their versions should be updated when the main packages above are updated.
elliptic-curve = "0.9"
digest = "0.9"
generic-array = "0.14"
aead = { version = "0.4", features = ["heapless"] }
ecdsa = "0.11"
signature = "1.3"
rand_core = { version = "0.6", default-features = false, features = ["getrandom"] }
typenum = "1.13" # typenum is a 2018-edition crate starting from 1.13
getrandom = { version = "0.2", default-features = false, features = ["js"] }
subtle = { version = "2.4", default-features = false }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
path = "bench/bench.rs"
harness = false
